#!/usr/bin/env bash
# Checking if the script is called with the correct number of parameters - >4

if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    # Assign parameters to variables
    file_path="$1"
    server_ip="$2"
    username="$3"
    ssh_key="$4"

    # Use scp to transfer the file to the user's home directory on the server
    scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip:~/"
fi
